Дз_1
Skaletto07/Java_2 pull request #2
Opened 2022-03-22 14:15 UTC by Skaletto07

Выполнил дз, но не без помощи instanceof

2022-03-23 17:34 UTC, efserg requested changes

2022-03-23 17:34 UTC, efserg commented on geekbrains.java_2_lesson_1/src/main/java/lesson_1/Main.java
> +                    if (catty.isCondition()) {
Эти проверки лучше делать в классах-участниках

2022-03-23 17:34 UTC, efserg commented on geekbrains.java_2_lesson_1/src/main/java/lesson_1/Main.java
> +                    if (o1 instanceof Wall) {
instanceOf не позволяет расширять иерархию наследования без изменения клиентского кода

2022-03-23 17:34 UTC, efserg commented on geekbrains.java_2_lesson_1/src/main/java/lesson_1/Main.java
> +                    Cat catty = (Cat) o;
С препятствиями еще понятно, но какой смысл в приведении к Cat, Robot и Human?

2022-03-23 17:34 UTC, efserg commented on geekbrains.java_2_lesson_1/src/main/java/lesson_1/Robot.java
> +    public void run() {
Передайте сюда препятствие - все сильно упростится

2022-03-24 13:23 UTC, Skaletto07 commented on geekbrains.java_2_lesson_1/src/main/java/lesson_1/Main.java
> +                    Cat catty = (Cat) o;
чтобы вызвать метод определенных классов, ведь по заданию нельзя было использовать наследование у участников

2022-03-27 18:37 UTC, merged