HomeWork 6 is done!
Skaletto07/Java_2 pull request #7
Opened 2022-04-10 10:51 UTC by Skaletto07

Не придумал, как удобнее закрывать и сервер и клиент, закрываются при отправке и сервером и клиентом /end

2022-04-12 13:47 UTC, efserg requested changes
Не пойму, где отправка сообщения на серверной стороне?
Жду исправлений в соответствии с заданием

2022-04-12 17:55 UTC, Skaletto07 commented
отправка сообщения на серверной стороне на 27 строке сервера, а как сделать так, чтобы по несколько строк можно было отправлять, не разобрался!

2022-04-12 18:42 UTC, Skaletto07 commented
Немного переделал, теперь и сервер и клиент могут отправлять независимое количество сообщений

2022-04-13 16:47 UTC, efserg approved these changes
Да, теперь все ок.

2022-04-13 17:19 UTC, merged